---
- name: Fact Finder
  hosts: group2
  tasks:
    - debug:
        msg:
          - "System architecture is {{ ansible_architecture }}"
          - "System is {{ ansible_hostname }}"
          - "System has {{ ansible_memory_mb.real }} of ram"
